export const layersConfig = [
  { id: "gisTPI:Actividades_Agropecuarias", title: "Actividades Agropecuarias" },
  { id: "gisTPI:Actividades_Economicas", title: "Actividades Económicas" },
  { id: "gisTPI:Complejo_de_Energia_Ene", title: "Complejo de Energía" },
  { id: "gisTPI:Curso_de_Agua_Hid", title: "Curso de Agua" },
  { id: "gisTPI:Curvas_de_Nivel", title: "Curvas de Nivel" },
  { id: "gisTPI:Edif_Construcciones_Turisticas", title: "Construcciones Turísticas" },
  { id: "gisTPI:Edif_Depor_y_Esparcimiento", title: "Deporte y Esparcimiento" },
  { id: "gisTPI:Edif_Educacion", title: "Educación" },
  { id: "gisTPI:Edif_Religiosos", title: "Edificios Religiosos" },
  { id: "gisTPI:Edificio_Publico_IPS", title: "Edificio Público" },
  { id: "gisTPI:Edificio_de_Salud_IPS", title: "Edificio de Salud" },
  { id: "gisTPI:Edificio_de_Seguridad_IPS", title: "Edificio de Seguridad" },
  { id: "gisTPI:Edificios_Ferroviarios", title: "Edificios Ferroviarios" },
  { id: "gisTPI:Ejido", title: "Ejido" },
  { id: "gisTPI:Espejo_de_Agua_Hid", title: "Espejos de Agua" },
];
